name: Build & publish common lib
on:
  push:
    branches:
      - develop

jobs:
  build_and_publish_for_win:
    name: Publish (windows platform)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          gradle build
          gradle windowsX64Test
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false
      - name: Publish
        run: gradle -s -i publishWindowsX64PublicationToMavenRepository
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
  build_and_publish_for_mac:
    name: Publish (macOS platform)
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: gradle build
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false
      - name: Publish
        run: |
          gradle -s -i check
          gradle -s -i publish
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
